apiVersion: apps/v1
kind: Deployment
metadata:
  name: akka-test
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: railway-crossing
  template:
    metadata:
      labels:
        app: railway-crossing
    spec:
      serviceAccountName: akka-test
      imagePullSecrets:
        - name: regcred
      containers:
        - name: akka-test
          image: docker.io/gregor2323/akka
          imagePullPolicy: Always
          env:
            - name: AKKA_REMOTING_BIND_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            httpGet:
              path: /ready
              port: management
          livenessProbe:
            httpGet:
              path: /alive
              port: management
          ports:
            - name: remoting
              containerPort: 2551
              protocol: TCP
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: railway-crossing
  name: railway-crossing-service
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: remoting
      port: 2551
      protocol: TCP
      targetPort: 2551
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
  selector:
    app: railway-crossing