services:
  simulate-sensors:
    image: gregor2323/akka-railway-simple-sensors:latest
    pull_policy: always
    environment:
      - NATS_URL=nats-server:4222
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://telegraf:4317
    networks:
      - railway-crossing-net

networks:
  railway-crossing-net:
    external: true