configs:
  telegraf_config:
    file: ./telegraf.conf
services:

#  influxdb:
#    image: "influxdb:2"
#    ports:
#      - "8086:8086"
#    environment:
#      - DOCKER_INFLUXDB_INIT_MODE=setup
#      - DOCKER_INFLUXDB_INIT_USERNAME=admin
#      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
#      - DOCKER_INFLUXDB_INIT_ORG=org
#      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
#      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=bzO10KmR8x
#  telegraf:
#    image: "telegraf:latest"
#    ports:
#      - "4317:4317"
#    configs:
#      - source: telegraf_config
#        target: /etc/telegraf/telegraf.conf
  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SAMPLING_TYPE=const
      - SAMPLING_PARAM=1
  nats-server:
    image: "nats"
    ports:
      - "4222:4222"
  akka-railway-service:
      image: "gregor2323/akka-railway-crossing-service:latest"
      pull_policy: always
      ports:
        - "8000:8000"
      environment:
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
