services:
  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SAMPLING_TYPE=const
      - SAMPLING_PARAM=1
  nats-server:
    image: "nats"
    ports:
      - "4222:4222"
  akka-railway-service:
      image: "gregor2323/akka-railway-crossing-service:latest"
      pull_policy: always
      ports:
        - "8000:8000"
      environment:
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
