akka{
    loggers = ["akka.event.slf4j.Slf4jLogger"]
    loglevel = "DEBUG"
    logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"

    http{
        server {
            default-http-port = 8000
        }
    }

    actor{
        provider = "cluster"
    }

    remote.artery{
        enabled = on
        transport = tcp
        canonical.hostname = "127.0.0.1"
        canonical.port = 4711
    }

    cluster{
        seed-nodes = [
            "akka://RailWayCrossing@127.0.0.1:4711"
        ]
    }
}