apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  namespace: cloud
  name: akka-test
spec:
  workload:
    manifests:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: akka-test
          namespace: default
        spec:
          selector:
            matchLabels:
              app: akka-test
          template:
            metadata:
              labels:
                app: akka-test
            spec:
              containers:
                - name: akka-test
                  image: akka-test
                  readinessProbe:
                    httpGet:
                      path: /ready
                      port: management
                  livenessProbe:
                    httpGet:
                      path: /alive
                      port: management
                  ports:
                    - name: management
                      containerPort: 8558
                      protocol: TCP
                    - name: http
                      containerPort: 8080
                      protocol: TCP