akka{
    http{
        server {
            default-http-port = 8000
        }
    }

    actor{
        provider = "cluster"
        serializers
        {
            jackson-json = "akka.serialization.jackson.JacksonJsonSerializer"
        }
        serialization-bindings
        {
            "actors.messages.SerializableMessage" = jackson-json
        }
    }

    remote.artery{
        enabled = on
        transport = tcp
        canonical.port = 2551
    }

    cluster {
            shutdown-after-unsuccessful-join-seed-nodes = 60s
        }
    coordinated-shutdown.exit-jvm = on

    management{
        cluster.bootstrap {
            contact-point-discovery {
              discovery-method = kubernetes-api
            }
        }
    }
    cluster.http.management {
       route-providers-read-only = false
    }
}