akka{
    http{
        server {
            default-http-port = 8000
        }
    }

    actor{
        provider = "cluster"
    }

    remote.artery{
        enabled = on
        transport = tcp
        canonical.port = 2551
    }

    cluster {
            shutdown-after-unsuccessful-join-seed-nodes = 60s
        }
    coordinated-shutdown.exit-jvm = on

    management{
        cluster.bootstrap {
            contact-point-discovery {
              discovery-method = kubernetes-api
            }
        }
    }
    cluster.http.management {
       route-providers-read-only = false
    }


    discovery {
        method = akka-dns
    }


    persistence {
        journal {
            plugin = "akka.persistence.journal.inmem"
            auto-start-journals = []
        }
    }
}