akka{
    license-key = 3CecWl2jcmc8QqNN4nQsZI4TpxdYl3Ijd8Qp642LL5qZ8LLpw9EJ2Os48IfbCPDcH88gtMgLxtAU20BKaqbEN73i9tgIUZzmgYv7NN6pfMIRvbGWp7qAkhFYyIY5qYmzD5VW6DR3vamlwu3BHw86LUcII5F6Lh9CA9eGB0h7oWsoME

    http{
        server {
            default-http-port = 8000
        }
    }

    actor{
        provider = "cluster"
    }

    cluster {
            seed-nodes = [
              "akka://railway-crossing@192.168.64.67:2551"
            ]
            shutdown-after-unsuccessful-join-seed-nodes = 60s
        }
    coordinated-shutdown.exit-jvm = on

    management{
            http {
              bind-hostname = "192.168.64.67"
              port = 8558
            }
            hostname = "192.168.64.67"
    }

    cluster.http.management {
       route-providers-read-only = true
    }

    discovery {
        method = akka-dns
    }
}