{{- $prefix := .Values.prefix -}}
{{- $types := .Values.types -}}
{{- range $crossingID := until (int .Values.crossings) -}}
{{- range $types }}
---
# This is the template for creating a railway-node within Kubernetes
#
# This template is inspired by the official Akka-Documentation:
#
# https://doc.akka.io/libraries/akka-management/current/kubernetes-deployment/preparing-for-production.html#deployment-spec
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$prefix}}{{ $crossingID}}-{{.|lower}}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: railway-crossing
  template:
    metadata:
      labels:
        app: railway-crossing
    spec:
      serviceAccountName: akka-node
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{$prefix}}{{ $crossingID}}-{{.|lower}}
          image: docker.io/gregor2323/akka-railway-crossing-node
          imagePullPolicy: Always
          env:
            - name: AKKA_REMOTING_BIND_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CROSSING_ID
              value:  {{$prefix}}{{ $crossingID}}
            - name: COMPONENT_TYPE
              value: {{ . }}
          readinessProbe:
            httpGet:
              path: /ready
              port: management
          livenessProbe:
            httpGet:
              path: /alive
              port: management
          ports:
            - name: management
              containerPort: 8558
              protocol: TCP
{{- end }}
{{- end }}
---
# This template provides the service to send signals towards the Signal-API: /src/main/java/actors/api/*
apiVersion: v1
kind: Service
metadata:
  labels:
    app: railway-crossing
  name: railway-crossing-signals
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: signal
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: railway-crossing