# This template deploys the service that is invoked by the Akka-Application and makes it accessible within the cluster
  {{ if eq .Values.service_invocation "Remote"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: railway-crossing-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: railway-crossing-service
  template:
    metadata:
      labels:
        app: railway-crossing-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: railway-crossing-service
          image: docker.io/gregor2323/akka-railway-crossing-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-service
  name: railway-crossing-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: railway-crossing-service
    {{end}}