akka{
    license-key = 3CecWl2VbUN8W6X6rqLeAq4TsXUbuLDqf4uUhbWpMc9i4KGyP6Htda748IfbCPERUM8gtMyCO1OvV0BKaugH7mncEgZ0QzUtZt3Ewbi6zhpR8QD6sP9xjjA810b05k40mq9d0brxHPzQ0Oe0UY8wxyRTiUFz8tp66aLbx2NAnHfB

    actor{
        provider = "cluster"
    }

    remote.artery{
        enabled = on
        transport = tcp
        canonical.hostname = "localhost"
        canonical.hostname = ${?AKKA_ARTERY_HOST}
        bind.hostname = 0.0.0.0
        canonical.port = 2551
    }

    cluster {
        seed-nodes.0 = "akka://surveillance-system@localhost:2551"
        seed-nodes.0 = ${?AKKA_CLUSTER_SEED_NODE}

        shutdown-after-unsuccessful-join-seed-nodes = 60s
    }
    coordinated-shutdown.exit-jvm = on

    management{
            http {
              bind-hostname = "localhost"
              port = 8558
            }
            hostname = "localhost"
    }

    cluster.http.management {
       route-providers-read-only = true
    }
}